# Generated by Django 4.2.8 on 2024-02-21 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0001_initial'),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='essay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='essays.essay'),
        ),
    ]
